version: '3.8'

services:
  app:
    build: .
    ports:
      - "3030:3030"
    volumes:
      - ./telegram_sessions:/app/telegram_sessions
      - ./logs:/app/logs
      - ./data:/app/data
      - ./users.db:/app/users.db
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=3030
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    secrets:
      - aws_access_key
      - aws_secret_key
      - encryption_key
      - admin_key

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
    
secrets:
  aws_access_key:
    file: ./secrets/aws_access_key.txt
  aws_secret_key:
    file: ./secrets/aws_secret_key.txt
  encryption_key:
    file: ./secrets/encryption_key.txt
  admin_key:
    file: ./secrets/admin_key.txt 